import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import {
  Badge,
  Button,
  Card,
  Container,
  Metric,
  Section,
  SectionHeading,
} from "@/components/ui/design";
import { impactMetrics, journey } from "@/data/experience";
import { principles } from "@/data/principles";

import { WorkSystemCard, type WorkSystem } from "@/components/workspaces/SystemsConsole";

const selectedWork: WorkSystem[] = [
  {
    title: "Enterprise Workflow Automation Platform", status: "Production workspace", impact: "≈ $30M value surfaced", category: "Orchestration Engine", accent: "emerald",
    metrics: [{ id: "cycle", label: "Cycle reduction", value: "40%", context: "Measured against the manual operating cadence after approvals, exception routing, and completion checks moved into one orchestrated flow." }, { id: "controls", label: "Checkpoints", value: "6", context: "Approval and audit checkpoints keep automation bounded while preserving a reviewable history." }, { id: "state", label: "Completion", value: "Live", context: "The workspace separates active, completed, warning, and idle states so operators know what needs attention." }],
    nodes: [{ id: "n01", label: "Intake", detail: "Structured requests", status: "complete", related: ["n02", "n04"], meta: "Requests enter with enough context for eligibility review, routing, and audit reconstruction." }, { id: "n02", label: "Eligibility", detail: "Workflow gates", status: "complete", related: ["n01", "n03"], meta: "Deterministic gates decide whether work can proceed automatically or needs approval." }, { id: "n03", label: "Approval", detail: "Control checkpoint", status: "active", related: ["n02", "n04", "n06"], meta: "Approval checkpoints make ownership explicit before execution changes operational state." }, { id: "n04", label: "Executor", detail: "Queued actions", status: "active", related: ["n03", "n05"], meta: "Execution history shows queued, retried, completed, and exception outcomes without burying operators in logs." }, { id: "n05", label: "Exceptions", detail: "Retry or review", status: "warning", related: ["n04", "n06"], meta: "Exceptions stay visible as reviewable work, with retry state and resolution owner close to the task." }, { id: "n06", label: "Audit trail", detail: "Completion record", status: "idle", related: ["n03", "n05"], meta: "Every action resolves into a reconstructable completion record for operational review." }],
    lanes: [{ id: "pre", label: "Pre-flight", items: ["Eligibility gates", "Approval checkpoint", "Dependency check"], dependsOn: ["n01", "n02", "n03"] }, { id: "run", label: "Execution", items: ["Queued work", "Retry state", "Exception routing"], dependsOn: ["n04", "n05"] }, { id: "audit", label: "Control", items: ["Audit trail", "Outcome review", "Completion status"], dependsOn: ["n03", "n06"] }],
    signals: [{ label: "Queue healthy", state: "active", detail: "Work is moving through the current operating window." }, { label: "Exception review", state: "warning", detail: "Ambiguous items are isolated for human approval." }, { label: "Audit complete", state: "complete", detail: "Completed actions include owner, state, and decision context." }],
    decisions: [{ path: "Automate only bounded work", rationale: "The orchestration layer handles high-confidence paths and routes ambiguous cases before execution.", outcome: "Reduced cycle time while keeping riskier work reviewable.", related: ["n02", "n03", "n05"] }, { path: "Make history operational", rationale: "Execution history is treated as a first-class workspace object, not an afterthought.", outcome: "Operators can explain completion, retry, and exception states quickly.", related: ["n04", "n05", "n06"] }], map: "automation"
  },
  {
    title: "Unified Analytics Platform", status: "Trusted metric layer", impact: "Reusable KPI foundation", category: "BI Control Plane", accent: "cyan",
    metrics: [{ id: "sources", label: "Sources", value: "Many", context: "Multiple upstream business systems resolve into governed definitions and refresh status." }, { id: "defs", label: "Definitions", value: "One", context: "The semantic layer gives teams a shared place to inspect metric ownership and definition notes." }, { id: "consumers", label: "Consumers", value: "Multi-team", context: "Dashboards and decision forums consume the same governed metric layer." }],
    nodes: [{ id: "n01", label: "Business sources", detail: "Upstream contracts", status: "complete", related: ["n02"], meta: "Source ownership and refresh status are visible before metric consumers see the number." }, { id: "n02", label: "Quality checks", detail: "Refresh status", status: "active", related: ["n01", "n03"], meta: "Refresh checks identify whether upstream movement affects downstream trust." }, { id: "n03", label: "Semantic layer", detail: "Governed definitions", status: "active", related: ["n02", "n04", "n05"], meta: "Definitions, owners, and accepted business grain sit together so teams stop reconciling separate versions." }, { id: "n04", label: "Metric catalog", detail: "Ownership metadata", status: "complete", related: ["n03", "n06"], meta: "Catalog metadata explains who owns a metric, what changed, and where it is consumed." }, { id: "n05", label: "Dashboards", detail: "Consumer views", status: "idle", related: ["n03", "n06"], meta: "Consumer views inherit definition context instead of redefining logic per dashboard." }, { id: "n06", label: "Decision forums", detail: "Aligned reads", status: "idle", related: ["n04", "n05"], meta: "Downstream forums can trace KPI movement back to source, refresh, and definition context." }],
    lanes: [{ id: "lineage", label: "Lineage", items: ["Source-to-metric path", "Upstream status", "Downstream consumers"], dependsOn: ["n01", "n02", "n03"] }, { id: "governance", label: "Governance", items: ["Metric owner", "Definition note", "Quality status"], dependsOn: ["n03", "n04"] }, { id: "consume", label: "Consumption", items: ["Executive view", "Team drill-down", "Decision forum"], dependsOn: ["n04", "n05", "n06"] }],
    signals: [{ label: "Refresh completed", state: "complete", detail: "Latest governed metric refresh is available to consumers." }, { label: "Owner assigned", state: "active", detail: "Critical definitions show business ownership." }, { label: "Lineage reviewed", state: "complete", detail: "Upstream and downstream dependencies are inspectable." }],
    decisions: [{ path: "Trust before dashboard volume", rationale: "A governed semantic layer reduces reconciliation before new surfaces are added.", outcome: "Teams can reuse KPI definitions with less metric drift.", related: ["n03", "n04", "n05"] }, { path: "Show lineage near consumption", rationale: "Consumers need upstream context at the moment they interpret a number.", outcome: "Decision forums can distinguish data freshness from business movement.", related: ["n01", "n02", "n06"] }], map: "lineage"
  },
  {
    title: "Self-Service Decision Platform", status: "Governed exploration space", impact: "Reusable reporting system", category: "Executive Workspace", accent: "violet",
    metrics: [{ id: "paths", label: "Question paths", value: "Curated", context: "Executives enter through business questions, not blank dashboards." }, { id: "drift", label: "Metric drift", value: "Reduced", context: "Filters and drill-downs preserve governed definitions while enabling exploration." }, { id: "actions", label: "Recommended action", value: "Visible", context: "Each decision path includes context, tradeoffs, and measurable follow-up." }],
    nodes: [{ id: "n01", label: "KPI scorecard", detail: "Executive read", status: "active", related: ["n02", "n04"], meta: "Scorecards summarize business state and expose filters for accountable drill-down." }, { id: "n02", label: "Filters", detail: "Business slices", status: "idle", related: ["n01", "n03"], meta: "Filters narrow the question without changing the approved definition." }, { id: "n03", label: "Drill-down", detail: "Question path", status: "active", related: ["n02", "n05"], meta: "Guided drill-downs answer recurring business questions in a repeatable order." }, { id: "n04", label: "Context", detail: "Narrative notes", status: "complete", related: ["n01", "n06"], meta: "Decision context keeps interpretation, caveats, and owner notes beside the KPI." }, { id: "n05", label: "Tradeoffs", detail: "Decision options", status: "warning", related: ["n03", "n06"], meta: "Tradeoffs compare action paths and show why one recommendation is preferred." }, { id: "n06", label: "Outcome", detail: "Measured follow-up", status: "idle", related: ["n04", "n05"], meta: "Recommended actions close with an owner and the metric that will prove impact." }],
    lanes: [{ id: "entry", label: "Entry points", items: ["KPI lookup", "Operating question", "Filter context"], dependsOn: ["n01", "n02"] }, { id: "explore", label: "Exploration", items: ["Segment compare", "Trend explain", "Root-cause path"], dependsOn: ["n02", "n03", "n05"] }, { id: "decide", label: "Decision support", items: ["Rationale", "Recommended action", "Follow-up metric"], dependsOn: ["n04", "n05", "n06"] }],
    signals: [{ label: "Decision context ready", state: "active", detail: "The selected KPI includes narrative and owner context." }, { label: "Tradeoff under review", state: "warning", detail: "Decision options are visible before action is selected." }, { label: "Outcome measure set", state: "complete", detail: "Recommended action includes a measurable follow-up." }],
    decisions: [{ path: "Start from business questions", rationale: "The workspace guides leaders through repeatable questions rather than exposing every chart at once.", outcome: "Faster interpretation and fewer one-off reporting requests.", related: ["n01", "n03", "n04"] }, { path: "Pair action with evidence", rationale: "Recommendations are only useful when the tradeoff and follow-up metric are visible.", outcome: "Decision makers leave with rationale, owner, and expected outcome.", related: ["n05", "n06"] }], map: "workspace"
  },
  {
    title: "Guided Operations Workflow", status: "Operator decision tool", impact: "Complex actions simplified", category: "Operations Control Center", accent: "amber",
    metrics: [{ id: "alerts", label: "Alerts", value: "Triage", context: "Signals route into queues and playbooks with visible resolution state." }, { id: "queues", label: "Queues", value: "Mapped", context: "Fresh opportunities, coverage review, source validation, and discovery experience work are separated by action type." }, { id: "resolution", label: "Resolution", value: "Tracked", context: "Decision paths record rationale and next state for operational follow-through." }],
    nodes: [{ id: "n01", label: "Alert stream", detail: "Product signals", status: "active", related: ["n02", "n03"], meta: "Signals such as coverage expanded, refresh completed, source validation finished, and search quality reviewed enter triage." }, { id: "n02", label: "Queue router", detail: "Work allocation", status: "active", related: ["n01", "n04"], meta: "Queues distinguish fresh opportunities, coverage review, source validation, and discovery experience work." }, { id: "n03", label: "Case state", detail: "Open or resolved", status: "warning", related: ["n01", "n05"], meta: "Case state makes active review, waiting, and resolved work easy to separate." }, { id: "n04", label: "Playbook", detail: "Guided action", status: "complete", related: ["n02", "n05"], meta: "Playbooks prompt review signal, validate impact, and prioritize product action." }, { id: "n05", label: "Decision path", detail: "Rationale", status: "active", related: ["n03", "n04", "n06"], meta: "Operators can see why a route was chosen and what product outcome it supports." }, { id: "n06", label: "Resolution", detail: "Closed loop", status: "idle", related: ["n05"], meta: "Resolution status records the product outcome, owner, and next review state." }],
    lanes: [{ id: "alert", label: "Signals", items: ["Coverage expanded", "Refresh completed", "Search quality reviewed"], dependsOn: ["n01", "n03"] }, { id: "queue", label: "Queues", items: ["Fresh opportunities", "Coverage review", "Source validation"], dependsOn: ["n02", "n04"] }, { id: "decision", label: "Product decisions", items: ["Review signal", "Validate impact", "Prioritize product action"], dependsOn: ["n05", "n06"] }],
    signals: [{ label: "Coverage expanded", state: "complete", detail: "New employer-source coverage is reflected in discovery." }, { label: "Refresh completed", state: "complete", detail: "Fresh opportunities are available after the latest refresh." }, { label: "Source validation finished", state: "active", detail: "Coverage review is ready for product action." }, { label: "Search quality reviewed", state: "warning", detail: "Discovery experience queue has an item to evaluate." }],
    decisions: [{ path: "Route signal to action", rationale: "Operators need to understand whether a signal requires review, validation, or product prioritization.", outcome: "Work moves through queues with a clear resolution state.", related: ["n01", "n02", "n05"] }, { path: "Keep product language focused", rationale: "The control center communicates user-facing product state and operational priority.", outcome: "HirePulse remains commercially safe while still feeling operational.", related: ["n04", "n05", "n06"] }], map: "workflow"
  },
];

export default function Home() {
  return (
    <>
      <Navbar />
      <main>
        <Section className="min-h-[92svh] pt-32"><Container><div className="grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div className="reveal"><Badge>Product engineer • Data • AI</Badge><h1 className="mt-8 text-6xl font-semibold leading-none tracking-[-0.08em] sm:text-8xl lg:text-9xl">BUILT TO<br />SOLVE.</h1><p className="mt-8 text-3xl font-light tracking-[-0.04em] text-zinc-200 sm:text-5xl">Turning complexity into clarity.</p><p className="mt-8 max-w-2xl text-lg leading-8 text-zinc-400">I design and build data platforms, AI-powered products, and automation systems that transform complex business challenges into scalable, measurable solutions.</p><div className="mt-10 flex flex-wrap gap-3"><Button href="/products">See My Products</Button><Button href="/experience" variant="secondary">Explore Experience</Button></div><div className="mt-10 flex flex-wrap gap-3"><Badge>Amazon</Badge><Badge>8+ Years</Badge><Badge>Building HirePulse</Badge></div></div><Card className="reveal"><div className="grid gap-4">{["Problem", "Data", "Automation", "AI", "Decision"].map((item, index) => <div key={item} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-zinc-950/60 p-4"><span className="flex size-9 items-center justify-center rounded-full bg-emerald-300/10 text-emerald-300">{index + 1}</span><span className="text-lg text-white">{item}</span><span className="ml-auto text-zinc-600">→</span></div>)}</div></Card></div></Container></Section>
        <Section>
          <Container>
            <SectionHeading eyebrow="Selected Work" title="Production systems, opened like internal workspaces." text="Each view is structured around the operating model: inputs, controls, execution paths, signals, and the decisions that shaped the system." />
            <div className="space-y-10">{selectedWork.map((work, index) => <WorkSystemCard key={work.title} work={work} index={index} />)}</div>
          </Container>
        </Section>
        <Section><Container><SectionHeading eyebrow="Engineering principles" title="A practical operating system for hard problems." /><div className="grid gap-5 md:grid-cols-2">{principles.map((p) => <Card key={p.number}><p className="text-emerald-300">{p.number}</p><h3 className="mt-4 text-2xl font-semibold">{p.title}</h3><p className="mt-3 text-zinc-400">{p.summary}</p></Card>)}</div></Container></Section>
        <Section><Container><Card className="grid gap-8 lg:grid-cols-2"><div><Badge>The Lab</Badge><h2 className="mt-6 text-4xl font-semibold tracking-[-0.04em]">Active product bench.</h2></div><div><h3 className="text-2xl font-semibold">HirePulse</h3><p className="mt-4 leading-8 text-zinc-400">A job discovery platform that helps job seekers find fresh opportunities from company career sites in one searchable experience.</p><div className="mt-6 grid grid-cols-2 gap-3 text-sm text-zinc-300"><span className="rounded-2xl border border-white/10 bg-zinc-950/60 p-3">135,000+ career sites</span><span className="rounded-2xl border border-white/10 bg-zinc-950/60 p-3">Hourly refresh</span></div><div className="mt-6"><Button href="/lab/hirepulse" variant="secondary">Open Lab workspace</Button></div></div></Card></Container></Section>
        <Section><Container><SectionHeading eyebrow="Business impact" title="Built around outcomes that can be explained." /><div className="grid gap-5 md:grid-cols-3">{impactMetrics.map((m) => <Metric key={m.label} {...m} />)}</div></Container></Section>
        <Section><Container><SectionHeading eyebrow="Experience journey" title="From enterprise data systems to AI product exploration." /><div className="flex flex-wrap gap-3">{journey.map((item) => <Badge key={item}>{item}</Badge>)}</div></Container></Section>
        <Section><Container><Card><h2 className="text-4xl font-semibold tracking-[-0.04em]">Let’s build something meaningful.</h2><p className="mt-5 max-w-2xl leading-8 text-zinc-400">Whether you’re building a product, modernizing data platforms, or exploring AI, I’d love to connect.</p><div className="mt-8"><Button href="/contact">Contact Gowri</Button></div></Card></Container></Section>
      </main>
      <Footer />
    </>
  );
}
