import Link from "next/link";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Badge, Button, Card, Container, Heading, Section, SectionHeading } from "@/components/ui/design";
import { products, type Product } from "@/data/products";

export default function CaseStudyPage({ product }: { product: Product }) {
  const index = products.findIndex((item) => item.slug === product.slug);
  const next = products[(index + 1) % products.length];
  return <><Navbar /><main><Section className="pt-32"><Container><Heading eyebrow="Product case study" title={product.title} text={product.positioning} /><div className="mt-8 flex flex-wrap gap-2">{product.capabilities.map((cap)=><Badge key={cap}>{cap}</Badge>)}</div></Container></Section><Section><Container><div className="grid gap-6 lg:grid-cols-3"><Card><h2 className="text-xl font-semibold">Context</h2><p className="mt-4 leading-7 text-zinc-400">{product.context}</p></Card><Card><h2 className="text-xl font-semibold">Problem</h2><p className="mt-4 leading-7 text-zinc-400">{product.problem}</p></Card><Card><h2 className="text-xl font-semibold">Outcome</h2><p className="mt-4 leading-7 text-zinc-400">{product.outcome}</p></Card></div></Container></Section><Section><Container><SectionHeading eyebrow="System workflow" title="From complexity to an operating layer people can trust." /><ol className="grid gap-4 md:grid-cols-3 lg:grid-cols-6">{product.workflow.map((step,i)=><li key={step} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><span className="text-sm text-emerald-300">0{i+1}</span><p className="mt-3 font-semibold">{step}</p></li>)}</ol></Container></Section><Section><Container><div className="grid gap-6 lg:grid-cols-2"><List title="Constraints" items={product.constraints} /><List title="Approach" items={product.approach} /><List title="Key decisions" items={product.decisions} /><List title="Lessons" items={product.lessons} /></div></Container></Section><Section><Container><Card className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm uppercase tracking-[0.2em] text-zinc-500">Next case study</p><Link href={`/products/${next.slug}`} className="mt-2 block text-2xl font-semibold hover:text-emerald-300">{next.title}</Link></div><Button href="/contact">Discuss a system</Button></Card></Container></Section></main><Footer /></>;
}
function List({ title, items }: { title: string; items: readonly string[] }) { return <Card><h2 className="text-2xl font-semibold">{title}</h2><ul className="mt-5 space-y-4 text-zinc-400">{items.map((item)=><li className="flex gap-3" key={item}><span className="mt-2 size-1.5 shrink-0 rounded-full bg-emerald-300" />{item}</li>)}</ul></Card>; }
